spring.datasource.url=jdbc:h2:file:./data/notesdb;auto_server=true
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true

# Align backend limits with Vaadin upload max file size.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB
